name: Extract PR Comments to GitHub Project
on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches: [main, develop, feature]
    states: [open]
  workflow_dispatch: {}

jobs: 
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract PR Comments and Sync to GitHub Projects
        run: echo "Extracting PR comments for syncing..."